model_list:
  - model_name: "github/gpt-4o"
    litellm_params: 
      model: "github/gpt-4o"
      api_key: "os.environ/OPENAI_LIKE_API_KEY"
  - model_name: "github/gpt-4o-mini"
    litellm_params: 
      model: "github/gpt-4o-mini"
      api_key: "os.environ/OPENAI_LIKE_API_KEY"


